# Generated by Django 5.0.4 on 2024-08-22 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"verbose_name": "Banking Customer"},
        ),
    ]
