# Generated by Django 5.0.4 on 2024-08-25 17:59

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customer_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True),
        ),
    ]
