# Generated by Django 5.0.4 on 2024-08-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customer_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("SELECT", ""), ("MALE", "Male"), ("FEMALE", "Female")],
                null=True,
            ),
        ),
    ]
