# Generated by Django 5.0.4 on 2024-08-22 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0002_bank_customer_bank_isfc_code_account_transaction_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bank",
            old_name="isfc_code",
            new_name="ifsc_code",
        ),
    ]
