# Generated by Django 5.0.4 on 2024-08-22 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0003_rename_isfc_code_bank_ifsc_code"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Bank",
        ),
    ]
