# Generated by Django 5.0.4 on 2024-08-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0004_delete_bank"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="amount",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="remark",
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("DEBIT", "Debit"),
                    ("CREDIT", "Credit"),
                    ("TRANSFER", "Transfer"),
                    ("RECEIVE", "Receive"),
                ]
            ),
        ),
    ]
