# Generated by Django 5.0.4 on 2024-08-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0005_transaction_amount_transaction_remark_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_number",
            field=models.BigIntegerField(),
        ),
    ]
