# Generated by Django 5.0.4 on 2024-08-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0007_alter_transaction_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("DEBIT", "Debit"),
                    ("CREDIT", "Credit"),
                    ("TRANSFER", "Transfer"),
                    ("RECEIVE", "Receive"),
                    ("CREATE", "Create"),
                ]
            ),
        ),
    ]
