# Generated by Django 5.0.4 on 2024-08-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0009_alter_transaction_options_alter_transaction_remark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="balance",
            field=models.FloatField(default=0),
        ),
    ]
